version: "3.9"
services:
  ############################################### cAdvisor ###############################################
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: 'docker-dev'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - default
    ports:
      - 9080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ############################################### Node-exporter ###############################################
  docker-dev-node-exporter:
    image: prom/node-exporter:latest
    hostname: 'docker-dev'
    networks:
      - default
    ports:
      - 9100:9100
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s
